[package]
name = "flow-bot"
version = "0.2.5"
edition = "2024"
authors = ["KevinT3Hu"]
description = "An onebot-11 SDK that simplifies bot creation."
repository = "https://github.com/KevinT3Hu/flow-bot.git"
license = "AGPL-3.0-only"
build = "build.rs"

[dependencies]
anyhow = { version = "1.0" }
async-trait = "0.1.89"
axum = { version = "0.8.8", features = ["ws"], optional = true }
bcrypt = { version = "0.18.0", optional = true }
cap-std = { version = "4.0.2" }
chrono = { version = "0.4" }
clap = { version = "4.5.60", features = ["derive"] }
dashmap = "6.1"
flow-bot-extractor = { path = "../flow-bot-extractor", version = "0.1.0" }
flow-bot-onebot11 = { path = "../flow-bot-onebot11", version = "0.1.0", features = [
    "api",
] }
futures = { version = "0.3.32" }
jsonwebtoken = { version = "10.3.0", optional = true }
notify-debouncer-mini = { version = "0.7.0" }
rust-embed = { version = "8.11.0", optional = true, features = ["axum"] }
semver = { version = "1.0" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = [
    "macros",
    "sync",
    "time",
    "rt-multi-thread",
] }
tokio-stream = { version = "0.1", features = ["sync"], optional = true }
tokio-tungstenite = "0.28.0"
toml = "1.0.3"
tower-http = { version = "0.6.8", features = ["fs", "cors"], optional = true }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.5", optional = true }
uuid = { version = "1.21.0", features = ["v4"] }
wasmtime = { version = "42.0.1" }
wasmtime-wasi = { version = "42.0.1" }
wit-bindgen = "0.53.1"
witgen = "0.15.0"

[dev-dependencies]
tokio = { version = "1.49.0", features = ["rt"] }

[features]
default = []
api-server = [
    "dep:axum",
    "dep:tokio-stream",
    "dep:tower-http",
    "dep:jsonwebtoken",
    "dep:bcrypt",
    "dep:url",
]
webui = ["api-server", "dep:rust-embed"]
