//! Type conversions between wasmtime-generated types and flow-bot-onebot11 types
//!
//! This module provides `From` trait implementations to convert between the
//! types generated by wasmtime's bindgen macro and the native Rust types
//! defined in the flow-bot-onebot11 crate.

use crate::runtime::flow_bot::onebot11::types as wit;
use flow_bot_onebot11::{api, event::message, message::message_ext::MessageExt};

// ============================================================================
// Macros for Bidirectional Conversions
// ============================================================================

/// Macro to implement bidirectional `From` for types with identical field names.
/// Simple fields are passed directly; Option<T> fields use `.map(Into::into)`.
macro_rules! impl_bidirectional_simple {
    ($native:ty, $wit:ty, $($field:ident),+ $(,)?) => {
        impl From<$native> for $wit {
            fn from(value: $native) -> Self {
                Self {
                    $($field: value.$field),*
                }
            }
        }

        impl From<$wit> for $native {
            fn from(value: $wit) -> Self {
                Self {
                    $($field: value.$field),*
                }
            }
        }
    };
}

/// Macro to implement bidirectional `From` for types with optional fields that need mapping.
macro_rules! impl_bidirectional_option {
    ($native:ty, $wit:ty, $($field:ident),+ $(,)?) => {
        impl From<$native> for $wit {
            fn from(value: $native) -> Self {
                Self {
                    $($field: value.$field.map(Into::into)),*
                }
            }
        }

        impl From<$wit> for $native {
            fn from(value: $wit) -> Self {
                Self {
                    $($field: value.$field.map(Into::into)),*
                }
            }
        }
    };
}

/// Macro to implement bidirectional `From` for enums with identical variants.
macro_rules! impl_bidirectional_enum {
    ($native:ty, $wit:ty, $($variant:ident),+ $(,)?) => {
        impl From<$native> for $wit {
            fn from(value: $native) -> Self {
                match value {
                    $(<$native>::$variant => <$wit>::$variant),*
                }
            }
        }

        impl From<$wit> for $native {
            fn from(value: $wit) -> Self {
                match value {
                    $(<$wit>::$variant => <$native>::$variant),*
                }
            }
        }
    };
}

// ============================================================================
// API Response Types
// ============================================================================

impl_bidirectional_enum!(
    api::ApiRetStatus,
    wit::ApiRetStatus,
    Ok,
    Async,
    Failed,
);

// BotStatus has a renamed field (data <-> extra_data)
impl From<api::BotStatus> for wit::BotStatus {
    fn from(status: api::BotStatus) -> Self {
        Self {
            online: status.online,
            good: status.good,
            extra_data: status.data.into_iter().collect(),
        }
    }
}

impl From<wit::BotStatus> for api::BotStatus {
    fn from(status: wit::BotStatus) -> Self {
        Self {
            online: status.online,
            good: status.good,
            data: status.extra_data.into_iter().collect(),
        }
    }
}

impl_bidirectional_simple!(
    api::SendMessageResponse,
    wit::SendMessageResponse,
    message_id,
);

// ============================================================================
// Sender Types
// ============================================================================

impl_bidirectional_enum!(
    message::SenderSex,
    wit::SenderSex,
    Male,
    Female,
    Unknown,
);

impl_bidirectional_option!(
    message::PrivateSenderInfo,
    wit::PrivateSenderInfo,
    user_id,
    nickname,
    sex,
    age,
);

impl_bidirectional_enum!(
    message::GroupSenderRole,
    wit::GroupSenderRole,
    Owner,
    Admin,
    Member,
);

impl From<message::GroupSenderInfo> for wit::GroupSenderInfo {
    fn from(info: message::GroupSenderInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.map(Into::into),
            age: info.age,
            area: info.area,
            level: info.level,
            role: info.role.map(Into::into),
            title: info.title,
        }
    }
}

impl From<wit::GroupSenderInfo> for message::GroupSenderInfo {
    fn from(info: wit::GroupSenderInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.map(Into::into),
            age: info.age,
            area: info.area,
            level: info.level,
            role: info.role.map(Into::into),
            title: info.title,
        }
    }
}

impl_bidirectional_simple!(
    message::GroupAnonymousInfo,
    wit::GroupAnonymousInfo,
    id,
    name,
    flag,
);

// ============================================================================
// Get Message Response Types
// ============================================================================

// GetMessageType has complex enum variants - keep manual implementation
impl From<api::GetMessageType> for wit::GetMessageType {
    fn from(ty: api::GetMessageType) -> Self {
        match ty {
            api::GetMessageType::Private { sender } => Self::Private(sender.into()),
            api::GetMessageType::Group { sender } => Self::Group(sender.into()),
        }
    }
}

impl From<wit::GetMessageType> for api::GetMessageType {
    fn from(ty: wit::GetMessageType) -> Self {
        match ty {
            wit::GetMessageType::Private(sender) => Self::Private { sender: sender.into() },
            wit::GetMessageType::Group(sender) => Self::Group { sender: sender.into() },
        }
    }
}

// GetMessageResponse has a custom field (message uses extract_plain_text)
impl From<api::GetMessageResponse> for wit::GetMessageResponse {
    fn from(response: api::GetMessageResponse) -> Self {
        Self {
            time: response.time,
            message_id: response.message_id,
            real_id: response.real_id,
            message: response.message.extract_plain_text(),
            msg_type: response.ty.into(),
        }
    }
}

// GetForwardResponse has a custom field (message uses extract_plain_text)
impl From<api::GetForwardResponse> for wit::GetForwardResponse {
    fn from(response: api::GetForwardResponse) -> Self {
        Self {
            message: response.message.extract_plain_text(),
        }
    }
}

// ============================================================================
// User Info Types
// ============================================================================

impl_bidirectional_simple!(api::LoginInfo, wit::LoginInfo, user_id, nickname);

impl From<api::StrangerInfo> for wit::StrangerInfo {
    fn from(info: api::StrangerInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.into(),
            age: info.age,
        }
    }
}

impl From<wit::StrangerInfo> for api::StrangerInfo {
    fn from(info: wit::StrangerInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.into(),
            age: info.age,
        }
    }
}

impl_bidirectional_simple!(api::FriendInfo, wit::FriendInfo, user_id, nickname, remark);

// ============================================================================
// Group Info Types
// ============================================================================

impl_bidirectional_simple!(
    api::GroupInfoResponse,
    wit::GroupInfoResponse,
    group_id,
    group_name,
    member_count,
    max_member_count,
);

impl From<api::GroupMemberInfo> for wit::GroupMemberInfo {
    fn from(info: api::GroupMemberInfo) -> Self {
        Self {
            group_id: info.group_id,
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.into(),
            age: info.age,
            area: info.area,
            join_time: info.join_time,
            last_sent_time: info.last_sent_time,
            level: info.level,
            role: info.role.into(),
            unfriendly: info.unfriendly,
            title: info.title,
            title_expire_time: info.title_expire_time,
            card_changeable: info.card_changeable,
        }
    }
}

impl From<wit::GroupMemberInfo> for api::GroupMemberInfo {
    fn from(info: wit::GroupMemberInfo) -> Self {
        Self {
            group_id: info.group_id,
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.into(),
            age: info.age,
            area: info.area,
            join_time: info.join_time,
            last_sent_time: info.last_sent_time,
            level: info.level,
            role: info.role.into(),
            unfriendly: info.unfriendly,
            title: info.title,
            title_expire_time: info.title_expire_time,
            card_changeable: info.card_changeable,
        }
    }
}

// ============================================================================
// Group Honor Types
// ============================================================================

impl_bidirectional_simple!(
    api::TalkativeInfo,
    wit::TalkativeInfo,
    user_id,
    nickname,
    avatar,
    day_count,
);

impl_bidirectional_simple!(
    api::HonorInfo,
    wit::HonorInfo,
    user_id,
    nickname,
    avatar,
    description,
);

// GroupHonorInfo has complex Option<Vec<T>> fields requiring custom mapping
impl From<api::GroupHonorInfo> for wit::GroupHonorInfo {
    fn from(info: api::GroupHonorInfo) -> Self {
        Self {
            group_id: info.group_id,
            current_talkative: info.current_talkative.map(Into::into),
            talkative_list: info
                .talkative_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            performer_list: info
                .performer_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            legend_list: info
                .legend_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            strong_newbie_list: info
                .strong_newbie_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            emotion_list: info
                .emotion_list
                .map(|v| v.into_iter().map(Into::into).collect()),
        }
    }
}

impl From<wit::GroupHonorInfo> for api::GroupHonorInfo {
    fn from(info: wit::GroupHonorInfo) -> Self {
        Self {
            group_id: info.group_id,
            current_talkative: info.current_talkative.map(Into::into),
            talkative_list: info
                .talkative_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            performer_list: info
                .performer_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            legend_list: info
                .legend_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            strong_newbie_list: info
                .strong_newbie_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            emotion_list: info
                .emotion_list
                .map(|v| v.into_iter().map(Into::into).collect()),
        }
    }
}

impl_bidirectional_enum!(
    api::GroupHonorType,
    wit::GroupHonorType,
    Talkative,
    Performer,
    Legend,
    StrongNewbie,
    Emotion,
    All,
);

// ============================================================================
// Credential Types
// ============================================================================

impl_bidirectional_simple!(api::GetCookiesResponse, wit::GetCookiesResponse, cookies);

impl_bidirectional_simple!(
    api::GetCsrfTokenResponse,
    wit::GetCsrfTokenResponse,
    token,
);

impl_bidirectional_simple!(
    api::GetCredentialsResponse,
    wit::GetCredentialsResponse,
    cookies,
    csrf_token,
);

// ============================================================================
// File and Media Types
// ============================================================================

impl_bidirectional_simple!(api::GetFileResponse, wit::GetFileResponse, file);

impl_bidirectional_enum!(
    api::RecordFormat,
    wit::RecordFormat,
    Mp3,
    Amr,
    Wma,
    M4a,
    Spx,
    Ogg,
    Wav,
    Flac,
);

impl_bidirectional_simple!(api::CanSendResponse, wit::CanSendResponse, yes);

// ============================================================================
// Version Info Types
// ============================================================================

// VersionInfo has a renamed field (data <-> extra_data)
impl From<api::VersionInfo> for wit::VersionInfo {
    fn from(info: api::VersionInfo) -> Self {
        Self {
            app_name: info.app_name,
            app_version: info.app_version,
            protocol_version: info.protocol_version,
            extra_data: info.data.into_iter().collect(),
        }
    }
}

impl From<wit::VersionInfo> for api::VersionInfo {
    fn from(info: wit::VersionInfo) -> Self {
        Self {
            app_name: info.app_name,
            app_version: info.app_version,
            protocol_version: info.protocol_version,
            data: info.extra_data.into_iter().collect(),
        }
    }
}

// ============================================================================
// Request Sub-types
// ============================================================================

impl_bidirectional_enum!(
    flow_bot_onebot11::event::request::GroupRequestSubType,
    wit::GroupRequestSubType,
    Add,
    Invite,
);
