//! Type conversions between wasmtime-generated types and flow-bot-onebot11 types
//!
//! This module provides `From` trait implementations to convert between the
//! types generated by wasmtime's bindgen macro and the native Rust types
//! defined in the flow-bot-onebot11 crate.

use crate::runtime::flow_bot::onebot11::types as wit;
use flow_bot_onebot11::{api, event::message, message::segments};

// Re-export message segment types for convenience
pub use flow_bot_onebot11::message::segments::Segment as NativeMessageSegment;

// ============================================================================
// Macros for Bidirectional Conversions
// ============================================================================

/// Macro to implement bidirectional `From` for types with identical field names.
/// Simple fields are passed directly; Option<T> fields use `.map(Into::into)`.
macro_rules! impl_bidirectional_simple {
    ($native:ty, $wit:ty, $($field:ident),+ $(,)?) => {
        impl From<$native> for $wit {
            fn from(value: $native) -> Self {
                Self {
                    $($field: value.$field),*
                }
            }
        }

        impl From<$wit> for $native {
            fn from(value: $wit) -> Self {
                Self {
                    $($field: value.$field),*
                }
            }
        }
    };
}

/// Macro to implement bidirectional `From` for types with optional fields that need mapping.
macro_rules! impl_bidirectional_option {
    ($native:ty, $wit:ty, $($field:ident),+ $(,)?) => {
        impl From<$native> for $wit {
            fn from(value: $native) -> Self {
                Self {
                    $($field: value.$field.map(Into::into)),*
                }
            }
        }

        impl From<$wit> for $native {
            fn from(value: $wit) -> Self {
                Self {
                    $($field: value.$field.map(Into::into)),*
                }
            }
        }
    };
}

/// Macro to implement bidirectional `From` for enums with identical variants.
macro_rules! impl_bidirectional_enum {
    ($native:ty, $wit:ty, $($variant:ident),+ $(,)?) => {
        impl From<$native> for $wit {
            fn from(value: $native) -> Self {
                match value {
                    $(<$native>::$variant => <$wit>::$variant),*
                }
            }
        }

        impl From<$wit> for $native {
            fn from(value: $wit) -> Self {
                match value {
                    $(<$wit>::$variant => <$native>::$variant),*
                }
            }
        }
    };
}

// ============================================================================
// API Response Types
// ============================================================================

impl_bidirectional_enum!(api::ApiRetStatus, wit::ApiRetStatus, Ok, Async, Failed,);

// BotStatus has a renamed field (data <-> extra_data)
impl From<api::BotStatus> for wit::BotStatus {
    fn from(status: api::BotStatus) -> Self {
        Self {
            online: status.online,
            good: status.good,
            extra_data: status.data.into_iter().collect(),
        }
    }
}

impl From<wit::BotStatus> for api::BotStatus {
    fn from(status: wit::BotStatus) -> Self {
        Self {
            online: status.online,
            good: status.good,
            data: status.extra_data.into_iter().collect(),
        }
    }
}

impl_bidirectional_simple!(
    api::SendMessageResponse,
    wit::SendMessageResponse,
    message_id,
);

// ============================================================================
// Sender Types
// ============================================================================

impl_bidirectional_enum!(message::SenderSex, wit::SenderSex, Male, Female, Unknown,);

impl_bidirectional_option!(
    message::PrivateSenderInfo,
    wit::PrivateSenderInfo,
    user_id,
    nickname,
    sex,
    age,
);

impl_bidirectional_enum!(
    message::GroupSenderRole,
    wit::GroupSenderRole,
    Owner,
    Admin,
    Member,
);

impl From<message::GroupSenderInfo> for wit::GroupSenderInfo {
    fn from(info: message::GroupSenderInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.map(Into::into),
            age: info.age,
            area: info.area,
            level: info.level,
            role: info.role.map(Into::into),
            title: info.title,
        }
    }
}

impl From<wit::GroupSenderInfo> for message::GroupSenderInfo {
    fn from(info: wit::GroupSenderInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.map(Into::into),
            age: info.age,
            area: info.area,
            level: info.level,
            role: info.role.map(Into::into),
            title: info.title,
        }
    }
}

impl_bidirectional_simple!(
    message::GroupAnonymousInfo,
    wit::GroupAnonymousInfo,
    id,
    name,
    flag,
);

// ============================================================================
// Get Message Response Types
// ============================================================================

// GetMessageType has complex enum variants - keep manual implementation
impl From<api::GetMessageType> for wit::GetMessageType {
    fn from(ty: api::GetMessageType) -> Self {
        match ty {
            api::GetMessageType::Private { sender } => Self::Private(sender.into()),
            api::GetMessageType::Group { sender } => Self::Group(sender.into()),
        }
    }
}

impl From<wit::GetMessageType> for api::GetMessageType {
    fn from(ty: wit::GetMessageType) -> Self {
        match ty {
            wit::GetMessageType::Private(sender) => Self::Private {
                sender: sender.into(),
            },
            wit::GetMessageType::Group(sender) => Self::Group {
                sender: sender.into(),
            },
        }
    }
}

// GetMessageResponse has a custom field (message uses JSON serialization to preserve formatting)
impl From<api::GetMessageResponse> for wit::GetMessageResponse {
    fn from(response: api::GetMessageResponse) -> Self {
        Self {
            time: response.time,
            message_id: response.message_id,
            real_id: response.real_id,
            message: serde_json::to_string(&response.message).unwrap_or_default(),
            msg_type: response.ty.into(),
        }
    }
}

// GetForwardResponse has a custom field (message uses JSON serialization to preserve formatting)
impl From<api::GetForwardResponse> for wit::GetForwardResponse {
    fn from(response: api::GetForwardResponse) -> Self {
        Self {
            message: serde_json::to_string(&response.message).unwrap_or_default(),
        }
    }
}

// ============================================================================
// User Info Types
// ============================================================================

impl_bidirectional_simple!(api::LoginInfo, wit::LoginInfo, user_id, nickname);

impl From<api::StrangerInfo> for wit::StrangerInfo {
    fn from(info: api::StrangerInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.into(),
            age: info.age,
        }
    }
}

impl From<wit::StrangerInfo> for api::StrangerInfo {
    fn from(info: wit::StrangerInfo) -> Self {
        Self {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.into(),
            age: info.age,
        }
    }
}

impl_bidirectional_simple!(api::FriendInfo, wit::FriendInfo, user_id, nickname, remark);

// ============================================================================
// Group Info Types
// ============================================================================

impl_bidirectional_simple!(
    api::GroupInfoResponse,
    wit::GroupInfoResponse,
    group_id,
    group_name,
    member_count,
    max_member_count,
);

impl From<api::GroupMemberInfo> for wit::GroupMemberInfo {
    fn from(info: api::GroupMemberInfo) -> Self {
        Self {
            group_id: info.group_id,
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.into(),
            age: info.age,
            area: info.area,
            join_time: info.join_time,
            last_sent_time: info.last_sent_time,
            level: info.level,
            role: info.role.into(),
            unfriendly: info.unfriendly,
            title: info.title,
            title_expire_time: info.title_expire_time,
            card_changeable: info.card_changeable,
        }
    }
}

impl From<wit::GroupMemberInfo> for api::GroupMemberInfo {
    fn from(info: wit::GroupMemberInfo) -> Self {
        Self {
            group_id: info.group_id,
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.into(),
            age: info.age,
            area: info.area,
            join_time: info.join_time,
            last_sent_time: info.last_sent_time,
            level: info.level,
            role: info.role.into(),
            unfriendly: info.unfriendly,
            title: info.title,
            title_expire_time: info.title_expire_time,
            card_changeable: info.card_changeable,
        }
    }
}

// ============================================================================
// Group Honor Types
// ============================================================================

impl_bidirectional_simple!(
    api::TalkativeInfo,
    wit::TalkativeInfo,
    user_id,
    nickname,
    avatar,
    day_count,
);

impl_bidirectional_simple!(
    api::HonorInfo,
    wit::HonorInfo,
    user_id,
    nickname,
    avatar,
    description,
);

// GroupHonorInfo has complex Option<Vec<T>> fields requiring custom mapping
impl From<api::GroupHonorInfo> for wit::GroupHonorInfo {
    fn from(info: api::GroupHonorInfo) -> Self {
        Self {
            group_id: info.group_id,
            current_talkative: info.current_talkative.map(Into::into),
            talkative_list: info
                .talkative_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            performer_list: info
                .performer_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            legend_list: info
                .legend_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            strong_newbie_list: info
                .strong_newbie_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            emotion_list: info
                .emotion_list
                .map(|v| v.into_iter().map(Into::into).collect()),
        }
    }
}

impl From<wit::GroupHonorInfo> for api::GroupHonorInfo {
    fn from(info: wit::GroupHonorInfo) -> Self {
        Self {
            group_id: info.group_id,
            current_talkative: info.current_talkative.map(Into::into),
            talkative_list: info
                .talkative_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            performer_list: info
                .performer_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            legend_list: info
                .legend_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            strong_newbie_list: info
                .strong_newbie_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            emotion_list: info
                .emotion_list
                .map(|v| v.into_iter().map(Into::into).collect()),
        }
    }
}

impl_bidirectional_enum!(
    api::GroupHonorType,
    wit::GroupHonorType,
    Talkative,
    Performer,
    Legend,
    StrongNewbie,
    Emotion,
    All,
);

// ============================================================================
// Credential Types
// ============================================================================

impl_bidirectional_simple!(api::GetCookiesResponse, wit::GetCookiesResponse, cookies);

impl_bidirectional_simple!(api::GetCsrfTokenResponse, wit::GetCsrfTokenResponse, token,);

impl_bidirectional_simple!(
    api::GetCredentialsResponse,
    wit::GetCredentialsResponse,
    cookies,
    csrf_token,
);

// ============================================================================
// File and Media Types
// ============================================================================

impl_bidirectional_simple!(api::GetFileResponse, wit::GetFileResponse, file);

impl_bidirectional_enum!(
    api::RecordFormat,
    wit::RecordFormat,
    Mp3,
    Amr,
    Wma,
    M4a,
    Spx,
    Ogg,
    Wav,
    Flac,
);

impl_bidirectional_simple!(api::CanSendResponse, wit::CanSendResponse, yes);

// ============================================================================
// Version Info Types
// ============================================================================

// VersionInfo has a renamed field (data <-> extra_data)
impl From<api::VersionInfo> for wit::VersionInfo {
    fn from(info: api::VersionInfo) -> Self {
        Self {
            app_name: info.app_name,
            app_version: info.app_version,
            protocol_version: info.protocol_version,
            extra_data: info.data.into_iter().collect(),
        }
    }
}

impl From<wit::VersionInfo> for api::VersionInfo {
    fn from(info: wit::VersionInfo) -> Self {
        Self {
            app_name: info.app_name,
            app_version: info.app_version,
            protocol_version: info.protocol_version,
            data: info.extra_data.into_iter().collect(),
        }
    }
}

// ============================================================================
// Request Sub-types
// ============================================================================

impl_bidirectional_enum!(
    flow_bot_onebot11::event::request::GroupRequestSubType,
    wit::GroupRequestSubType,
    Add,
    Invite,
);

// ============================================================================
// Message Segment Types
// ============================================================================

// ContactType enum - manual impl due to naming difference (QQ vs Qq)
impl From<segments::ContactType> for wit::ContactType {
    fn from(ty: segments::ContactType) -> Self {
        match ty {
            segments::ContactType::QQ => Self::Qq,
            segments::ContactType::Group => Self::Group,
        }
    }
}

impl From<wit::ContactType> for segments::ContactType {
    fn from(ty: wit::ContactType) -> Self {
        match ty {
            wit::ContactType::Qq => Self::QQ,
            wit::ContactType::Group => Self::Group,
        }
    }
}

// Simple segment types with identical fields
impl_bidirectional_simple!(segments::TextSegment, wit::TextSegment, text);
impl_bidirectional_simple!(segments::FaceSegment, wit::FaceSegment, id);
impl_bidirectional_simple!(segments::ImageSegment, wit::ImageSegment, file);
impl_bidirectional_simple!(segments::RecordSegment, wit::RecordSegment, file);
impl_bidirectional_simple!(segments::VideoSegment, wit::VideoSegment, file);
impl_bidirectional_simple!(segments::AtSegment, wit::AtSegment, qq);

// Unit-like struct segments
impl From<segments::DiceSegment> for wit::DiceSegment {
    fn from(_: segments::DiceSegment) -> Self {
        Self {}
    }
}

impl From<wit::DiceSegment> for segments::DiceSegment {
    fn from(_: wit::DiceSegment) -> Self {
        Self {}
    }
}

impl From<segments::ShakeSegment> for wit::ShakeSegment {
    fn from(_: segments::ShakeSegment) -> Self {
        Self {}
    }
}

impl From<wit::ShakeSegment> for segments::ShakeSegment {
    fn from(_: wit::ShakeSegment) -> Self {
        Self {}
    }
}

impl From<segments::AnonymousSegment> for wit::AnonymousSegment {
    fn from(_: segments::AnonymousSegment) -> Self {
        Self {}
    }
}

impl From<wit::AnonymousSegment> for segments::AnonymousSegment {
    fn from(_: wit::AnonymousSegment) -> Self {
        Self {}
    }
}

// Other simple segments
impl_bidirectional_simple!(segments::PokeSegment, wit::PokeSegment, ty, id);
impl_bidirectional_simple!(segments::ShareSegment, wit::ShareSegment, url, title);

// ContactSegment has a ContactType field
impl From<segments::ContactSegment> for wit::ContactSegment {
    fn from(segment: segments::ContactSegment) -> Self {
        Self {
            ty: segment.ty.into(),
            id: segment.id,
        }
    }
}

impl From<wit::ContactSegment> for segments::ContactSegment {
    fn from(segment: wit::ContactSegment) -> Self {
        Self {
            ty: segment.ty.into(),
            id: segment.id,
        }
    }
}

// LocationSegment with mixed required/optional fields - manual impl
impl From<segments::LocationSegment> for wit::LocationSegment {
    fn from(segment: segments::LocationSegment) -> Self {
        Self {
            lat: segment.lat,
            lon: segment.lon,
            title: segment.title,
            content: segment.content,
        }
    }
}

impl From<wit::LocationSegment> for segments::LocationSegment {
    fn from(segment: wit::LocationSegment) -> Self {
        Self {
            lat: segment.lat,
            lon: segment.lon,
            title: segment.title,
            content: segment.content,
        }
    }
}

// MusicSegment with mixed required/optional fields - manual impl
impl From<segments::MusicSegment> for wit::MusicSegment {
    fn from(segment: segments::MusicSegment) -> Self {
        Self {
            ty: segment.ty,
            id: segment.id,
            url: segment.url,
            audio: segment.audio,
            title: segment.title,
        }
    }
}

impl From<wit::MusicSegment> for segments::MusicSegment {
    fn from(segment: wit::MusicSegment) -> Self {
        Self {
            ty: segment.ty,
            id: segment.id,
            url: segment.url,
            audio: segment.audio,
            title: segment.title,
        }
    }
}

// Simple id-based segments
impl_bidirectional_simple!(segments::ReplySegment, wit::ReplySegment, id);
impl_bidirectional_simple!(segments::ForwardSegment, wit::ForwardSegment, id);
impl_bidirectional_simple!(segments::NodeSegment, wit::NodeSegment, id);
impl_bidirectional_simple!(segments::XmlSegment, wit::XmlSegment, data);
impl_bidirectional_simple!(segments::JsonSegment, wit::JsonSegment, data);

// Main Segment enum
impl From<segments::Segment> for wit::MessageSegment {
    fn from(segment: segments::Segment) -> Self {
        match segment {
            segments::Segment::Text(s) => Self::Text(s.into()),
            segments::Segment::Face(s) => Self::Face(s.into()),
            segments::Segment::Image(s) => Self::Image(s.into()),
            segments::Segment::Record(s) => Self::Record(s.into()),
            segments::Segment::Video(s) => Self::Video(s.into()),
            segments::Segment::At(s) => Self::At(s.into()),
            segments::Segment::Dice(s) => Self::Dice(s.into()),
            segments::Segment::Shake(s) => Self::Shake(s.into()),
            segments::Segment::Poke(s) => Self::Poke(s.into()),
            segments::Segment::Anonymous(s) => Self::Anonymous(s.into()),
            segments::Segment::Share(s) => Self::Share(s.into()),
            segments::Segment::Contact(s) => Self::Contact(s.into()),
            segments::Segment::Location(s) => Self::Location(s.into()),
            segments::Segment::Music(s) => Self::Music(s.into()),
            segments::Segment::Reply(s) => Self::Reply(s.into()),
            segments::Segment::Forward(s) => Self::Forward(s.into()),
            segments::Segment::Node(s) => Self::Node(s.into()),
            segments::Segment::Xml(s) => Self::Xml(s.into()),
            segments::Segment::Json(s) => Self::Json(s.into()),
        }
    }
}

impl From<wit::MessageSegment> for segments::Segment {
    fn from(segment: wit::MessageSegment) -> Self {
        match segment {
            wit::MessageSegment::Text(s) => Self::Text(s.into()),
            wit::MessageSegment::Face(s) => Self::Face(s.into()),
            wit::MessageSegment::Image(s) => Self::Image(s.into()),
            wit::MessageSegment::Record(s) => Self::Record(s.into()),
            wit::MessageSegment::Video(s) => Self::Video(s.into()),
            wit::MessageSegment::At(s) => Self::At(s.into()),
            wit::MessageSegment::Dice(s) => Self::Dice(s.into()),
            wit::MessageSegment::Shake(s) => Self::Shake(s.into()),
            wit::MessageSegment::Poke(s) => Self::Poke(s.into()),
            wit::MessageSegment::Anonymous(s) => Self::Anonymous(s.into()),
            wit::MessageSegment::Share(s) => Self::Share(s.into()),
            wit::MessageSegment::Contact(s) => Self::Contact(s.into()),
            wit::MessageSegment::Location(s) => Self::Location(s.into()),
            wit::MessageSegment::Music(s) => Self::Music(s.into()),
            wit::MessageSegment::Reply(s) => Self::Reply(s.into()),
            wit::MessageSegment::Forward(s) => Self::Forward(s.into()),
            wit::MessageSegment::Node(s) => Self::Node(s.into()),
            wit::MessageSegment::Xml(s) => Self::Xml(s.into()),
            wit::MessageSegment::Json(s) => Self::Json(s.into()),
        }
    }
}
