//! Type conversions between wasmtime-generated types and flow-bot-onebot11 types
//!
//! This module provides `From` trait implementations to convert between the
//! types generated by wasmtime's bindgen macro and the native Rust types
//! defined in the flow-bot-onebot11 crate.

use crate::runtime::flow_bot::onebot11::types as wit;
use flow_bot_onebot11::{api, event::message, message::message_ext::MessageExt};

// ============================================================================
// API Response Types
// ============================================================================

impl From<api::ApiRetStatus> for wit::ApiRetStatus {
    fn from(status: api::ApiRetStatus) -> Self {
        match status {
            api::ApiRetStatus::Ok => wit::ApiRetStatus::Ok,
            api::ApiRetStatus::Async => wit::ApiRetStatus::Async,
            api::ApiRetStatus::Failed => wit::ApiRetStatus::Failed,
        }
    }
}

impl From<wit::ApiRetStatus> for api::ApiRetStatus {
    fn from(status: wit::ApiRetStatus) -> Self {
        match status {
            wit::ApiRetStatus::Ok => api::ApiRetStatus::Ok,
            wit::ApiRetStatus::Async => api::ApiRetStatus::Async,
            wit::ApiRetStatus::Failed => api::ApiRetStatus::Failed,
        }
    }
}

impl From<api::BotStatus> for wit::BotStatus {
    fn from(status: api::BotStatus) -> Self {
        wit::BotStatus {
            online: status.online,
            good: status.good,
            extra_data: status.data.into_iter().collect(),
        }
    }
}

impl From<wit::BotStatus> for api::BotStatus {
    fn from(status: wit::BotStatus) -> Self {
        api::BotStatus {
            online: status.online,
            good: status.good,
            data: status.extra_data.into_iter().collect(),
        }
    }
}

impl From<api::SendMessageResponse> for wit::SendMessageResponse {
    fn from(response: api::SendMessageResponse) -> Self {
        wit::SendMessageResponse {
            message_id: response.message_id,
        }
    }
}

impl From<wit::SendMessageResponse> for api::SendMessageResponse {
    fn from(response: wit::SendMessageResponse) -> Self {
        api::SendMessageResponse {
            message_id: response.message_id,
        }
    }
}

// ============================================================================
// Sender Types
// ============================================================================

impl From<message::SenderSex> for wit::SenderSex {
    fn from(sex: message::SenderSex) -> Self {
        match sex {
            message::SenderSex::Male => wit::SenderSex::Male,
            message::SenderSex::Female => wit::SenderSex::Female,
            message::SenderSex::Unknown => wit::SenderSex::Unknown,
        }
    }
}

impl From<wit::SenderSex> for message::SenderSex {
    fn from(sex: wit::SenderSex) -> Self {
        match sex {
            wit::SenderSex::Male => message::SenderSex::Male,
            wit::SenderSex::Female => message::SenderSex::Female,
            wit::SenderSex::Unknown => message::SenderSex::Unknown,
        }
    }
}

impl From<message::PrivateSenderInfo> for wit::PrivateSenderInfo {
    fn from(info: message::PrivateSenderInfo) -> Self {
        wit::PrivateSenderInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.map(Into::into),
            age: info.age,
        }
    }
}

impl From<wit::PrivateSenderInfo> for message::PrivateSenderInfo {
    fn from(info: wit::PrivateSenderInfo) -> Self {
        message::PrivateSenderInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.map(Into::into),
            age: info.age,
        }
    }
}

impl From<message::GroupSenderRole> for wit::GroupSenderRole {
    fn from(role: message::GroupSenderRole) -> Self {
        match role {
            message::GroupSenderRole::Owner => wit::GroupSenderRole::Owner,
            message::GroupSenderRole::Admin => wit::GroupSenderRole::Admin,
            message::GroupSenderRole::Member => wit::GroupSenderRole::Member,
        }
    }
}

impl From<wit::GroupSenderRole> for message::GroupSenderRole {
    fn from(role: wit::GroupSenderRole) -> Self {
        match role {
            wit::GroupSenderRole::Owner => message::GroupSenderRole::Owner,
            wit::GroupSenderRole::Admin => message::GroupSenderRole::Admin,
            wit::GroupSenderRole::Member => message::GroupSenderRole::Member,
        }
    }
}

impl From<message::GroupSenderInfo> for wit::GroupSenderInfo {
    fn from(info: message::GroupSenderInfo) -> Self {
        wit::GroupSenderInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.map(Into::into),
            age: info.age,
            area: info.area,
            level: info.level,
            role: info.role.map(Into::into),
            title: info.title,
        }
    }
}

impl From<wit::GroupSenderInfo> for message::GroupSenderInfo {
    fn from(info: wit::GroupSenderInfo) -> Self {
        message::GroupSenderInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.map(Into::into),
            age: info.age,
            area: info.area,
            level: info.level,
            role: info.role.map(Into::into),
            title: info.title,
        }
    }
}

impl From<message::GroupAnonymousInfo> for wit::GroupAnonymousInfo {
    fn from(info: message::GroupAnonymousInfo) -> Self {
        wit::GroupAnonymousInfo {
            id: info.id,
            name: info.name,
            flag: info.flag,
        }
    }
}

impl From<wit::GroupAnonymousInfo> for message::GroupAnonymousInfo {
    fn from(info: wit::GroupAnonymousInfo) -> Self {
        message::GroupAnonymousInfo {
            id: info.id,
            name: info.name,
            flag: info.flag,
        }
    }
}

// ============================================================================
// Get Message Response Types
// ============================================================================

impl From<api::GetMessageType> for wit::GetMessageType {
    fn from(ty: api::GetMessageType) -> Self {
        match ty {
            api::GetMessageType::Private { sender } => wit::GetMessageType::Private(sender.into()),
            api::GetMessageType::Group { sender } => wit::GetMessageType::Group(sender.into()),
        }
    }
}

impl From<wit::GetMessageType> for api::GetMessageType {
    fn from(ty: wit::GetMessageType) -> Self {
        match ty {
            wit::GetMessageType::Private(sender) => api::GetMessageType::Private {
                sender: sender.into(),
            },
            wit::GetMessageType::Group(sender) => api::GetMessageType::Group {
                sender: sender.into(),
            },
        }
    }
}

impl From<api::GetMessageResponse> for wit::GetMessageResponse {
    fn from(response: api::GetMessageResponse) -> Self {
        wit::GetMessageResponse {
            time: response.time,
            message_id: response.message_id,
            real_id: response.real_id,
            message: response.message.extract_plain_text(),
            msg_type: response.ty.into(),
        }
    }
}

impl From<api::GetForwardResponse> for wit::GetForwardResponse {
    fn from(response: api::GetForwardResponse) -> Self {
        wit::GetForwardResponse {
            message: response.message.extract_plain_text(),
        }
    }
}

// ============================================================================
// User Info Types
// ============================================================================

impl From<api::LoginInfo> for wit::LoginInfo {
    fn from(info: api::LoginInfo) -> Self {
        wit::LoginInfo {
            user_id: info.user_id,
            nickname: info.nickname,
        }
    }
}

impl From<wit::LoginInfo> for api::LoginInfo {
    fn from(info: wit::LoginInfo) -> Self {
        api::LoginInfo {
            user_id: info.user_id,
            nickname: info.nickname,
        }
    }
}

impl From<api::StrangerInfo> for wit::StrangerInfo {
    fn from(info: api::StrangerInfo) -> Self {
        wit::StrangerInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.into(),
            age: info.age,
        }
    }
}

impl From<wit::StrangerInfo> for api::StrangerInfo {
    fn from(info: wit::StrangerInfo) -> Self {
        api::StrangerInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            sex: info.sex.into(),
            age: info.age,
        }
    }
}

impl From<api::FriendInfo> for wit::FriendInfo {
    fn from(info: api::FriendInfo) -> Self {
        wit::FriendInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            remark: info.remark,
        }
    }
}

impl From<wit::FriendInfo> for api::FriendInfo {
    fn from(info: wit::FriendInfo) -> Self {
        api::FriendInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            remark: info.remark,
        }
    }
}

// ============================================================================
// Group Info Types
// ============================================================================

impl From<api::GroupInfoResponse> for wit::GroupInfoResponse {
    fn from(info: api::GroupInfoResponse) -> Self {
        wit::GroupInfoResponse {
            group_id: info.group_id,
            group_name: info.group_name,
            member_count: info.member_count,
            max_member_count: info.max_member_count,
        }
    }
}

impl From<wit::GroupInfoResponse> for api::GroupInfoResponse {
    fn from(info: wit::GroupInfoResponse) -> Self {
        api::GroupInfoResponse {
            group_id: info.group_id,
            group_name: info.group_name,
            member_count: info.member_count,
            max_member_count: info.max_member_count,
        }
    }
}

impl From<api::GroupMemberInfo> for wit::GroupMemberInfo {
    fn from(info: api::GroupMemberInfo) -> Self {
        wit::GroupMemberInfo {
            group_id: info.group_id,
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.into(),
            age: info.age,
            area: info.area,
            join_time: info.join_time,
            last_sent_time: info.last_sent_time,
            level: info.level,
            role: info.role.into(),
            unfriendly: info.unfriendly,
            title: info.title,
            title_expire_time: info.title_expire_time,
            card_changeable: info.card_changeable,
        }
    }
}

impl From<wit::GroupMemberInfo> for api::GroupMemberInfo {
    fn from(info: wit::GroupMemberInfo) -> Self {
        api::GroupMemberInfo {
            group_id: info.group_id,
            user_id: info.user_id,
            nickname: info.nickname,
            card: info.card,
            sex: info.sex.into(),
            age: info.age,
            area: info.area,
            join_time: info.join_time,
            last_sent_time: info.last_sent_time,
            level: info.level,
            role: info.role.into(),
            unfriendly: info.unfriendly,
            title: info.title,
            title_expire_time: info.title_expire_time,
            card_changeable: info.card_changeable,
        }
    }
}

// ============================================================================
// Group Honor Types
// ============================================================================

impl From<api::TalkativeInfo> for wit::TalkativeInfo {
    fn from(info: api::TalkativeInfo) -> Self {
        wit::TalkativeInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            avatar: info.avatar,
            day_count: info.day_count,
        }
    }
}

impl From<wit::TalkativeInfo> for api::TalkativeInfo {
    fn from(info: wit::TalkativeInfo) -> Self {
        api::TalkativeInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            avatar: info.avatar,
            day_count: info.day_count,
        }
    }
}

impl From<api::HonorInfo> for wit::HonorInfo {
    fn from(info: api::HonorInfo) -> Self {
        wit::HonorInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            avatar: info.avatar,
            description: info.description,
        }
    }
}

impl From<wit::HonorInfo> for api::HonorInfo {
    fn from(info: wit::HonorInfo) -> Self {
        api::HonorInfo {
            user_id: info.user_id,
            nickname: info.nickname,
            avatar: info.avatar,
            description: info.description,
        }
    }
}

impl From<api::GroupHonorInfo> for wit::GroupHonorInfo {
    fn from(info: api::GroupHonorInfo) -> Self {
        wit::GroupHonorInfo {
            group_id: info.group_id,
            current_talkative: info.current_talkative.map(Into::into),
            talkative_list: info
                .talkative_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            performer_list: info
                .performer_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            legend_list: info
                .legend_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            strong_newbie_list: info
                .strong_newbie_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            emotion_list: info
                .emotion_list
                .map(|v| v.into_iter().map(Into::into).collect()),
        }
    }
}

impl From<wit::GroupHonorInfo> for api::GroupHonorInfo {
    fn from(info: wit::GroupHonorInfo) -> Self {
        api::GroupHonorInfo {
            group_id: info.group_id,
            current_talkative: info.current_talkative.map(Into::into),
            talkative_list: info
                .talkative_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            performer_list: info
                .performer_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            legend_list: info
                .legend_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            strong_newbie_list: info
                .strong_newbie_list
                .map(|v| v.into_iter().map(Into::into).collect()),
            emotion_list: info
                .emotion_list
                .map(|v| v.into_iter().map(Into::into).collect()),
        }
    }
}

impl From<api::GroupHonorType> for wit::GroupHonorType {
    fn from(ty: api::GroupHonorType) -> Self {
        match ty {
            api::GroupHonorType::Talkative => wit::GroupHonorType::Talkative,
            api::GroupHonorType::Performer => wit::GroupHonorType::Performer,
            api::GroupHonorType::Legend => wit::GroupHonorType::Legend,
            api::GroupHonorType::StrongNewbie => wit::GroupHonorType::StrongNewbie,
            api::GroupHonorType::Emotion => wit::GroupHonorType::Emotion,
            api::GroupHonorType::All => wit::GroupHonorType::All,
        }
    }
}

impl From<wit::GroupHonorType> for api::GroupHonorType {
    fn from(ty: wit::GroupHonorType) -> Self {
        match ty {
            wit::GroupHonorType::Talkative => api::GroupHonorType::Talkative,
            wit::GroupHonorType::Performer => api::GroupHonorType::Performer,
            wit::GroupHonorType::Legend => api::GroupHonorType::Legend,
            wit::GroupHonorType::StrongNewbie => api::GroupHonorType::StrongNewbie,
            wit::GroupHonorType::Emotion => api::GroupHonorType::Emotion,
            wit::GroupHonorType::All => api::GroupHonorType::All,
        }
    }
}

// ============================================================================
// Credential Types
// ============================================================================

impl From<api::GetCookiesResponse> for wit::GetCookiesResponse {
    fn from(response: api::GetCookiesResponse) -> Self {
        wit::GetCookiesResponse {
            cookies: response.cookies,
        }
    }
}

impl From<wit::GetCookiesResponse> for api::GetCookiesResponse {
    fn from(response: wit::GetCookiesResponse) -> Self {
        api::GetCookiesResponse {
            cookies: response.cookies,
        }
    }
}

impl From<api::GetCsrfTokenResponse> for wit::GetCsrfTokenResponse {
    fn from(response: api::GetCsrfTokenResponse) -> Self {
        wit::GetCsrfTokenResponse {
            token: response.token,
        }
    }
}

impl From<wit::GetCsrfTokenResponse> for api::GetCsrfTokenResponse {
    fn from(response: wit::GetCsrfTokenResponse) -> Self {
        api::GetCsrfTokenResponse {
            token: response.token,
        }
    }
}

impl From<api::GetCredentialsResponse> for wit::GetCredentialsResponse {
    fn from(response: api::GetCredentialsResponse) -> Self {
        wit::GetCredentialsResponse {
            cookies: response.cookies,
            csrf_token: response.csrf_token,
        }
    }
}

impl From<wit::GetCredentialsResponse> for api::GetCredentialsResponse {
    fn from(response: wit::GetCredentialsResponse) -> Self {
        api::GetCredentialsResponse {
            cookies: response.cookies,
            csrf_token: response.csrf_token,
        }
    }
}

// ============================================================================
// File and Media Types
// ============================================================================

impl From<api::GetFileResponse> for wit::GetFileResponse {
    fn from(response: api::GetFileResponse) -> Self {
        wit::GetFileResponse {
            file: response.file,
        }
    }
}

impl From<wit::GetFileResponse> for api::GetFileResponse {
    fn from(response: wit::GetFileResponse) -> Self {
        api::GetFileResponse {
            file: response.file,
        }
    }
}

impl From<api::RecordFormat> for wit::RecordFormat {
    fn from(format: api::RecordFormat) -> Self {
        match format {
            api::RecordFormat::Mp3 => wit::RecordFormat::Mp3,
            api::RecordFormat::Amr => wit::RecordFormat::Amr,
            api::RecordFormat::Wma => wit::RecordFormat::Wma,
            api::RecordFormat::M4a => wit::RecordFormat::M4a,
            api::RecordFormat::Spx => wit::RecordFormat::Spx,
            api::RecordFormat::Ogg => wit::RecordFormat::Ogg,
            api::RecordFormat::Wav => wit::RecordFormat::Wav,
            api::RecordFormat::Flac => wit::RecordFormat::Flac,
        }
    }
}

impl From<wit::RecordFormat> for api::RecordFormat {
    fn from(format: wit::RecordFormat) -> Self {
        match format {
            wit::RecordFormat::Mp3 => api::RecordFormat::Mp3,
            wit::RecordFormat::Amr => api::RecordFormat::Amr,
            wit::RecordFormat::Wma => api::RecordFormat::Wma,
            wit::RecordFormat::M4a => api::RecordFormat::M4a,
            wit::RecordFormat::Spx => api::RecordFormat::Spx,
            wit::RecordFormat::Ogg => api::RecordFormat::Ogg,
            wit::RecordFormat::Wav => api::RecordFormat::Wav,
            wit::RecordFormat::Flac => api::RecordFormat::Flac,
        }
    }
}

impl From<api::CanSendResponse> for wit::CanSendResponse {
    fn from(response: api::CanSendResponse) -> Self {
        wit::CanSendResponse { yes: response.yes }
    }
}

impl From<wit::CanSendResponse> for api::CanSendResponse {
    fn from(response: wit::CanSendResponse) -> Self {
        api::CanSendResponse { yes: response.yes }
    }
}

// ============================================================================
// Version Info Types
// ============================================================================

impl From<api::VersionInfo> for wit::VersionInfo {
    fn from(info: api::VersionInfo) -> Self {
        wit::VersionInfo {
            app_name: info.app_name,
            app_version: info.app_version,
            protocol_version: info.protocol_version,
            extra_data: info.data.into_iter().collect(),
        }
    }
}

impl From<wit::VersionInfo> for api::VersionInfo {
    fn from(info: wit::VersionInfo) -> Self {
        api::VersionInfo {
            app_name: info.app_name,
            app_version: info.app_version,
            protocol_version: info.protocol_version,
            data: info.extra_data.into_iter().collect(),
        }
    }
}

// ============================================================================
// Request Sub-types
// ============================================================================

impl From<wit::GroupRequestSubType> for flow_bot_onebot11::event::request::GroupRequestSubType {
    fn from(ty: wit::GroupRequestSubType) -> Self {
        match ty {
            wit::GroupRequestSubType::Add => {
                flow_bot_onebot11::event::request::GroupRequestSubType::Add
            }
            wit::GroupRequestSubType::Invite => {
                flow_bot_onebot11::event::request::GroupRequestSubType::Invite
            }
        }
    }
}

impl From<flow_bot_onebot11::event::request::GroupRequestSubType> for wit::GroupRequestSubType {
    fn from(ty: flow_bot_onebot11::event::request::GroupRequestSubType) -> Self {
        match ty {
            flow_bot_onebot11::event::request::GroupRequestSubType::Add => {
                wit::GroupRequestSubType::Add
            }
            flow_bot_onebot11::event::request::GroupRequestSubType::Invite => {
                wit::GroupRequestSubType::Invite
            }
        }
    }
}
