[package]
name = "flow-bot-extractor"
version = "0.1.0"
edition = "2024"
authors = ["KevinT3Hu"]
description = "Event extraction traits for flow-bot"
repository = "https://github.com/KevinT3Hu/flow-bot.git"
license = "AGPL-3.0-only"

[dependencies]
async-trait = "0.1.89"
flow-bot-onebot11 = { path = "../flow-bot-onebot11", version = "0.1.0" }
